
#############################################################################
# This config file is a necessary input file for the cactus GPU snakemake
# pipeline. 
#
# Before using this config file, first run cactus-prepare:
# <cactus_path> cactus-prepare <input_file> --outDir <output_dir> --jobStore <tmp_dir> --gpu
#
# Then replace the values below with the same paths in the fields below
# e.g.: 
# input_file: <input_file>
# input_file: /path/to/my/input/file.txt
#
# For working_dir, I prefer to make this one directory above my output_dir
#
# Gregg Thomas, Spring 2022
# Edited by Maggie Ko, Winter 2024
#############################################################################

working_dir: /home/mpg08/mko/pipelines/cactus/test_smk8_cactus

# cactus_path_link: docker://quay.io/comparative-genomics-toolkit/cactus:v2.9.3-gpu # we need to run 'cactus-prepare' first so we will pull this and have a .sif already
cactus_path: /home/mpg08/mko/pipelines/cactus/test_smk8_cactus/cactus_v2.9.3-gpu.sif

conda_env: /home/mpg08/mko/.conda/envs/cactus_env4 # This is the conda environment that snakemake and apptainer are installed in

input_file: /home/mpg08/mko/pipelines/cactus/test_smk8_cactus/seqfile.txt

cactus-prepare_output: /home/mpg08/mko/pipelines/cactus/test_smk8_cactus/output/seqfile.txt

output_dir: /home/mpg08/mko/pipelines/cactus/test_smk8_cactus/output

final_hal: /home/mpg08/mko/pipelines/cactus/test_smk8_cactus/output/file.hal

tmp_dir: /scratch/users/mko/g09.zE7V520Z

use_gpu: True

#############################################################################

mask_partition: "scc-gpu" 
mask_gpu: 2
mask_cpu: 24
mask_mem: "100gb" # strings with a number followed by a unit (B, KB, MB, GB, TB, PB, KiB, MiB, GiB, TiB, PiB
mask_runtime: "30m" # can be integer (in min) or string (e.g. "10m"), ms, s, m, h, d, w, y

##########################

blast_partition: "scc-gpu"
blast_gpu: 4
blast_cpu: 24
blast_mem: "200gb"
blast_runtime: "10m"

##########################

align_partition: "scc-gpu"
align_cpu: 24
align_mem: "450gb"
align_runtime: "24h"


##########################

convert_partition: "scc-cpu"
convert_cpu: 8
convert_mem: "8gb"
convert_runtime: "1h"

##########################

copy_partition: "scc-cpu"
copy_cpu: 1
copy_mem: "8gb"
copy_runtime: "1h"

##########################

append_partition: "scc-cpu"
append_cpu: 8
append_mem: "48gb"
append_runtime: "6h"

##########################

maf_partition: "scc-cpu"
maf_cpu: 8
maf_mem: "100gb"
maf_runtime: "24h"

##########################
