name: snakemake-env
channels:
  - bioconda
  - conda-forge
dependencies:
  - mamba
  - snakemake=8.25.5
  - apptainer=1.3.6
  - snakemake-executor-plugin-slurm
  - snakemake-executor-plugin-cluster-generic
  - snakemake-executor-plugin-cluster-sync
